# Generated by Django 4.0.2 on 2022-02-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptId', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emplId', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=500)),
                ('photoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
